spring:
  application.name: SpringTipsSpringModulith
  docker.compose.lifecycle-management: start_only
  sql.init.mode: always
  modulith:
    events.republish-outstanding-events-on-restart: true
    events.jdbc.schema-initialization.enabled: true
  datasource:
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: secret
  rabbitmq:
    username: myuser
    password: secret
  threads.virtual.enabled: true
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.probes.enabled: true
  info.env.enabled: true
  endpoint.health.show-details: always
  tracing:
    enabled: true
    sampling.probability: 1

logging:
  level:
    nu.westlin.springtipsspringmodulith: DEBUG
    org.springframework.boot.web.embedded.tomcat: INFO
    logging.level.org.springframework.jdbc: DEBUG
    root: WARN
